// @ts-nocheck
/**
 * @fileoverview Capability Catalog — auto-generated extension metadata
 * for the Capability Discovery Engine.
 *
 * The catalog JSON is generated by `scripts/generate-capability-catalog.mjs`
 * from all `manifest.json` files under `packages/agentos-extensions/registry/curated/`.
 *
 * This module re-exports the JSON array as a typed constant so the discovery
 * engine can index extensions that have no SKILL.md and are not otherwise
 * registered in the tool/channel/provider catalogs.
 *
 * @module @framers/agentos-extensions-registry/capability-catalog
 */

import catalogData from './capability-catalog.json' with { type: 'json' };

/**
 * A single entry in the auto-generated capability catalog.
 *
 * Each entry represents one extension manifest.json, reduced to the fields
 * needed by the discovery engine for indexing and semantic search.
 */
export interface CatalogEntry {
  /** Extension manifest ID (e.g., "com.framers.productivity.document-export") */
  id: string;
  /** Human-readable extension name */
  name: string;
  /** Natural language description — used for embedding generation */
  description: string;
  /** Primary category (first entry from manifest categories array) */
  category: string;
  /** Tool IDs exposed by this extension (from manifest extensions[].id) */
  tools: string[];
  /** Required secret keys for this extension to function */
  requiredSecrets: string[];
}

/**
 * Complete capability catalog — all extensions from manifest.json files.
 *
 * Generated at build time by `scripts/generate-capability-catalog.mjs`.
 * Used by the CapabilityDiscoveryEngine to index extensions that would
 * otherwise be invisible to semantic search (~81 extensions rescued).
 */
export const CAPABILITY_CATALOG: CatalogEntry[] = catalogData as CatalogEntry[];
